name = "getqueuelist"
type = "javascript"

account_id = "adbbba9f3192397bbf24db22cb72f221"
workers_dev = true
routes = ["api.pacman.ai/getqueuelist*", "queue.pacman.ai/*"]
zone_id = "e07181c90966336c97acf0d0aaffb76d"
target_type = "js"
usage_model = "bundled"

kv_namespaces = [
  {binding = "QUEUE", id = "3c3240983cc54463bf013053215b0426"},
  {binding = "TEAMS", id = "79309d4d11fb4f5ca3d6be5edca944d4"}
]

vars = { QUEUE_BROKER_PASS = "HW5S2][uD**xt\\6U", PACMAN_AI_GIT_APP_ID = "108842", PACMAN_AI_GIT_APP_CLIENT_ID = "Iv1.7e6f7bcf518ea8a9", PACMAN_AI_GIT_APP_CLIENT_SECRET = "d45934279215762490bd5080033b0edb07856a0e" }





