name = "createqueue"
type = "javascript"

account_id = "adbbba9f3192397bbf24db22cb72f221"
workers_dev = true
routes = ["https://addjobtoqueue.pacman.ai/*", "api.pacman.ai/addjobtoqueue/*"]
zone_id = "e07181c90966336c97acf0d0aaffb76d"
target_type = "js"
usage_model = "bundled"

kv_namespaces = [
  {binding = "QUEUE", id = "3c3240983cc54463bf013053215b0426"},
  {binding = "TEAMS", id = "c1af9d09e91442f5b6eb1252a9fd06de"}
]

vars = { QUEUE_BROKER_PASS = "HW5S2][uD**xt\\6U" }
